model_params:
  name: 'CategoricalVAE'
  in_channels: 3
  latent_dim: 512
  categorical_dim: 40
  temperature: 0.5
  anneal_rate: 0.00003
  anneal_interval: 100
  alpha: 1.0

data_params:
  data_path: "/home/jupyter/PEX/ImplementatieVAE"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: []
  max_epochs: 10000000

logging_params:
  save_dir: "logs/"
  name: "CategoricalVAE"
